In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random
import os
from keras.utils import img_to_array, array_to_img, to_categorical
from keras.layers import Conv2D, MaxPool2D, Dense, Flatten
from keras.optimizers import Adam
import cv2

In [2]:
vehicle = "../../dataset/data/vehicles/"
non_vehicle = "../../dataset/data/non-vehicles/"

In [3]:
def convert_image_array(image_path):
  try:
    image=cv2.imread(image_path)
    if image is not None:
      image=cv2.resize(image, (50,50))
      return (img_to_array(image))
    else:
      return np.array([])
  except Exception as e:
    print("Error", e)

In [4]:
path='../../dataset/data'
root_dir=os.listdir(path)
print(root_dir)

['non-vehicles', 'vehicles']


In [5]:
image_list, image_label=[],[]
temp=-1
for dir in root_dir:
  new_list = os.listdir(path+'/'+dir)
  temp+=1
  for i in new_list:
    img_path = path+'/'+dir+'/'+i 
    image_list.append(convert_image_array(img_path))
    image_label.append(temp)
print(image_label)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [6]:
len(image_list)

17760

In [7]:
np.unique(image_label, return_counts=True)

(array([0, 1]), array([8968, 8792], dtype=int64))

In [8]:
norm_image_list = np.array(image_list, dtype=np.float16)/255.0

In [9]:
norm_image_list = norm_image_list.reshape(-1, 50,50,3)
norm_image_list.shape

(17760, 50, 50, 3)

In [10]:
image_label=np.array(image_label)
image_list=np.array(image_list)

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(image_list, image_label, random_state=0)

In [12]:
# y_train=to_categorical(y_train)
# y_test=to_categorical(y_test)

In [13]:
print(y_train)

[1 0 0 ... 1 1 0]


In [14]:
print(type(X_train))

<class 'numpy.ndarray'>


In [15]:
X_train=np.asarray(X_train)
y_train=np.asarray(y_train)

In [16]:
len(y_train)

13320

In [17]:
from keras.models import Sequential
model = Sequential()
model.add(Conv2D(32,(3,3), padding='same', input_shape= (50,50,3),activation='relu'))
model.add(MaxPool2D(pool_size=(3,3)))
model.add(Conv2D(32,(3,3), padding='same', activation='relu'))
model.add(MaxPool2D(pool_size=(3,3)))
model.add(Conv2D(32,(3,3), padding='same', activation='relu'))
model.add(MaxPool2D(pool_size=(3,3)))
model.add(Flatten())
model.add(Dense(30,activation="relu"))
model.add(Dense(30,activation="relu"))
model.add(Dense(30,activation="relu"))
model.add(Dense(1,activation="sigmoid"))

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 50, 50, 32)        896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 16, 16, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 16, 16, 32)        9248      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 32)         0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 5, 5, 32)          9248      
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 1, 1, 32)         0

In [19]:
model.compile(loss='binary_crossentropy', optimizer=Adam(0.001), metrics=['accuracy'])

In [20]:
hist = model.fit(X_train,y_train, epochs=5, validation_split=0.2, batch_size=32)

Epoch 1/5
333/333 [==============================] - 13s 36ms/step - loss: 0.2998 - accuracy: 0.8776 - val_loss: 0.1933 - val_accuracy: 0.9234
Epoch 2/5
333/333 [==============================] - 13s 38ms/step - loss: 0.1260 - accuracy: 0.9534 - val_loss: 0.0816 - val_accuracy: 0.9718
Epoch 3/5
333/333 [==============================] - 12s 36ms/step - loss: 0.0982 - accuracy: 0.9649 - val_loss: 0.0667 - val_accuracy: 0.9756
Epoch 4/5
333/333 [==============================] - 12s 35ms/step - loss: 0.0687 - accuracy: 0.9754 - val_loss: 0.0500 - val_accuracy: 0.9816
Epoch 5/5
333/333 [==============================] - 12s 37ms/step - loss: 0.0712 - accuracy: 0.9756 - val_loss: 0.0788 - val_accuracy: 0.9715


In [21]:
ypred = model.predict(X_test)
ypred1 = np.round(ypred)
ypred1 = np.asarray(ypred1, dtype='int')

139/139 [==============================] - 2s 14ms/step


In [22]:
ypred1

array([[0],
       [0],
       [1],
       ...,
       [1],
       [0],
       [1]])

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, ypred1)
print(cm)
print(accuracy_score(y_test, ypred1))

[[2185   25]
 [ 113 2117]]
0.9689189189189189


In [24]:
model.save('vehicle.h5')